//
// Top-level class coordinating compiler and virtual machine.
//

import Foundation

// A context for interpreting Forth code.
// Main entry point for clients.
public class ForthEvaluator {
    let compiler = Compiler()
    let vm = VM()
    
    public init() {
        // Compile builtins implemented in Forth.
        evalOrDie(": CR 13 EMIT ;")
    }
    
    // Evaluate Forth source code.
    // Passing incomplete code fragments is supported.  For example eval(": foo") followed
    // by eval("42 ;").
    // Return true on success.
    // Report an error through handler passed to setErrorHandler() and return false on failure.
    public func eval(input: String) -> Bool {
        if let phrase = compiler.compile(input) {
            debug(.Evaluator, "compiled: \(phrase)")
            return vm.execPhrase(phrase)
        } else {
            return false
        }
    }

    public func setErrorHandler(handler: ForthErrorHandler) {
        compiler.errorHandler = handler
        vm.errorHandler = handler
    }
    
    // Return accumulated content generated by '.', EMIT, CR and co and reset it afterward.
    public func getAndResetOutput() -> String {
        let o = vm.output
        vm.output = ""
        return o
    }
    
    // Allow clients to manipulate argument stack directly.
    public var argStack : ForthStack<Int> {
        return vm.argStack
    }
    
    func evalOrDie(input: String) {
        if !eval(input) {
            println("failed to evaluate '\(input)'")
            exit(1)
        }
    }
}